### ISSUE TITLE
useGenericAuth: in `protect-all` mode ability to skip auth

### ISSUE THREAD

**Issue by saihaj** [dotansimha/envelop#886]
### Problem
With [`protect-all`](https://www.envelop.dev/plugins/use-generic-auth#option-1---protect-all) of `useGenericAuth` plugin it protects the entire schema but there should be way to skip some fields from this check. For example if there is a `login`/`signup` mutation that doesn't need to be protected.

### Solution
Add a directive option to `protect-all` option that will make a field publicly executable. We can call it `@public` or similar to [Redwood](https://redwoodjs.com/docs/directives#skipauth) `@skipAuth`

**Comment by n1ru4l** [comment]
This is already supported via SDL directives and field extensions
